filegroup(
    name = "client",
    srcs = [
        "//api/protos:lith_service_js_proto",
        "//api/protos:lith_service_js_grpc",
    ],
    visibility = ["//visibility:public"],
)

# webpack
exports_files([
    "src/index.js",
    "dist/index.js",
])